### PR TITLE
restarted feature branch favorite_food

### LINKED ISSUE #3: Add Eric's favorite foods.
Where are Eric's favorite foods at? Let's add them!!

### PR DESCRIPTION
**Pull request by harrelljam**
fixing capitalization
Closes #3

### CODE REVIEW

**Comment by harrelljam** [comment]
@Snejj made the requested change.

**Comment by Snejj** [comment]
@friqthehaw thanks for working on this! "Chick-fil-A" has a k in Chick, and the F isn't capitalized. Also, can you capitalize the n in nuggets? Thanks!

**Comment by harrelljam** [comment]
I have made the changes.  3rd times a charm?

**Comment by Snejj** [comment]
@friqthehaw looks great! Thanks.

**Pull request merged**
